# Generated by Django 3.0.3 on 2020-02-23 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initial_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='prefecture',
            new_name='your_pref',
        ),
    ]
